# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build linux-mipsle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Set up node
      uses: actions/setup-node@v4
      with:
          node-version: '18'
    - name: Frontend build          
      run: make build-frontend
      
    - name: Build
      run: GOOS=linux GOARCH=mipsle go build -ldflags "-s -w -X github.com/filebrowser/filebrowser/v2/version.CommitSHA=$FB_SHA -X github.com/filebrowser/filebrowser/v2/version.Version=$(date '+%Y%m%d')" -o ./publish/linux-mipsle
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: mipsle
        path: ./publish/linux-mipsle
